on: [push, pull_request]
name: Lint
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Lint
      uses: wandera/golangci-lint-action@v2.3.0
      env:
        CGO_ENABLED: 0
      with:
        version: v1.32
